### ISSUE TITLE
the tag close icon does not show in Firefox 56

### ISSUE THREAD

**Issue by sunnywalker** [haubek/bootstrap4c-tageditor#1]
switching the background SVG to full URL encoding (not just the < > entities) seems to fix it.

```
background: url("data:image/svg+xml;charset=utf8,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%3E%3Cpath%20fill%3D%27%23d9534f%27%20d%3D%27M19%206.41L17.59%205%2012%2010.59%206.41%205%205%206.41%2010.59%2012%205%2017.59%206.41%2019%2012%2013.41%2017.59%2019%2019%2017.59%2013.41%2012z%27%2F%3E%3C%2Fsvg%3E")
```

I'm not familiar with `sass-svg-uri` but it doesn't look like it supports full URI encoding, so a PR would not fit with your workflow.

**Comment by sunnywalker** [comment]
I installed the plugin via bower and the close icon shows, so maybe the issue is only with the demo on https://haubek.github.io/tageditor/?

**Comment by haubek** [comment]
Sorry yes. The demo hasn't been updated with latest version. I'll look into this.
